[package]
name = "im920_rs"
license = "MIT"
authors = ["syoch <syoch64@gmail.com>"]
description = "IM920sL library for Rust"
version = "1.0.5"
edition = "2021"

[build-dependencies]
cbindgen = "0.27.0"

[dependencies]
srobo_base = { features=["alloc"], version = "1.0.1" }

[features]
default = []
std = []